--  Native differential tests for Boundary_Segmentation (NOT part of the proof project).
--
--  Usage: test_segmentation <golden-cases> <synthetic-cases> [small]
--
--  Oracles:
--    * golden-cases     : 31 real cases (boundary_cases.txt) - expected spans of the old uncapped SQL
--    * synthetic-cases  : >= 2000 random cases generated by gen_cases.py by running the REAL
--                         sql/default_boundary_detection.sql through Python's sqlite3
--    * an independent in-test reference model (two explicit passes over heap arrays), used for
--      exhaustive small-N enumeration and for 64-bit magnitudes (N up to 2**62) where no SQL
--      oracle is feasible
--  Also covered: capacity handling (Overflow + exact Needed, never silent truncation), Spans'First
--  <> 1, invalid input (Spans untouched), >16 battles (the old cap is gone), 2M-boundary run.
--
--  "small" mode (used for the build with contracts/ghost spec EXECUTED, -gnata) restricts the
--  workload to cases with few boundaries, because the executable ghost specification is
--  quadratic/cubic by construction.
with Ada.Calendar;
with Ada.Command_Line;
with Ada.Strings.Unbounded;       use Ada.Strings.Unbounded;
with Ada.Text_IO;                 use Ada.Text_IO;
with Ada.Text_IO.Unbounded_IO;
with Ada.Unchecked_Deallocation;
with Interfaces;                  use Interfaces;

with Boundary_Segmentation;       use Boundary_Segmentation;

procedure Test_Segmentation is

   type Int_Vec is array (Positive range <>) of Long_Long_Integer;
   type Int_Vec_Access is access Int_Vec;
   procedure Free is new Ada.Unchecked_Deallocation (Int_Vec, Int_Vec_Access);

   type Bound_Access is access Boundary_Array;
   procedure Free is new Ada.Unchecked_Deallocation (Boundary_Array, Bound_Access);

   type Span_Access is access Span_Array;
   procedure Free is new Ada.Unchecked_Deallocation (Span_Array, Span_Access);

   Small : Boolean := False;
   Small_Boundary_Limit : constant := 6;

   Checks   : Natural := 0;
   Failures : Natural := 0;
   Cases_Run : Natural := 0;
   Calls     : Natural := 0;

   Poison : constant Span := (Start_Idx => 123_456_789, End_Idx => 987_654_321);

   procedure Check (Ok : Boolean; Msg : String) is
   begin
      Checks := Checks + 1;
      if not Ok then
         Failures := Failures + 1;
         if Failures <= 25 then
            Put_Line ("FAIL: " & Msg);
         end if;
      end if;
   end Check;

   ---------------------------------------------------------------------------
   --  Independent reference model: explicit merged list, then explicit segmentation.
   ---------------------------------------------------------------------------

   procedure Model_Into
     (N      : Long_Long_Integer;
      B      : Boundary_Array;
      Merged : in out Int_Vec;       --  scratch, length >= B'Length
      Res    : in out Span_Array;    --  result buffer, length >= B'Length + 1
      Count  : out Long_Long_Integer)
   is
      M     : Natural := 0;
      Start : Long_Long_Integer := 0;
   begin
      Count := 0;
      --  pass 1: merge
      for I in B'Range loop
         if B (I) >= 5 and then (M = 0 or else B (I) > Merged (Merged'First + M - 1) + 15) then
            M := M + 1;
            Merged (Merged'First + M - 1) := B (I);
         end if;
      end loop;
      --  pass 2: segmentation
      for K in 1 .. M loop
         if Merged (Merged'First + K - 1) - Start >= 10 then
            Count := Count + 1;
            Res (Res'First + Count - 1) :=
              (Start_Idx => Start, End_Idx => Merged (Merged'First + K - 1));
            Start := Merged (Merged'First + K - 1) + 1;
         end if;
      end loop;
      --  tail
      if N - 1 - Start >= 5 then
         Count := Count + 1;
         Res (Res'First + Count - 1) := (Start_Idx => Start, End_Idx => N - 1);
      end if;
   end Model_Into;

   function Model (N : Long_Long_Integer; B : Boundary_Array) return Span_Access is
      Merged : Int_Vec_Access := new Int_Vec (1 .. Natural (B'Length) + 1);
      Tmp    : Span_Access := new Span_Array (1 .. Long_Long_Integer (B'Length) + 1);
      R      : Long_Long_Integer;
   begin
      Model_Into (N, B, Merged.all, Tmp.all, R);
      declare
         Res : constant Span_Access := new Span_Array (1 .. R);
      begin
         Res.all := Tmp (1 .. R);
         Free (Merged);
         Free (Tmp);
         return Res;
      end;
   end Model;

   ---------------------------------------------------------------------------
   --  Run Segment with a given capacity / first index and compare with Exp (1-based).
   ---------------------------------------------------------------------------

   procedure Run_One
     (Name  : String;
      N     : Long_Long_Integer;
      B     : Boundary_Array;
      Exp   : Span_Array;
      Cap   : Long_Long_Integer;
      First : Position)
   is
      Total  : constant Long_Long_Integer := Exp'Length;
      Out_A  : Span_Access := new Span_Array (First .. First + Cap - 1);
      Needed : Span_Count;
      Status : Status_Kind;
      Same   : Boolean := True;
      Kept   : Boolean := True;
      Want   : constant Status_Kind := (if Total > Cap then Overflow else Ok);
      Wrote  : constant Long_Long_Integer := Long_Long_Integer'Min (Cap, Total);
   begin
      Out_A.all := (others => Poison);
      Segment (N, B, Out_A.all, Needed, Status);
      Calls := Calls + 1;
      Check (Status = Want, Name & ": status cap=" & Cap'Image & " total=" & Total'Image
             & " got " & Status'Image);
      Check (Needed = Total, Name & ": needed " & Needed'Image & " /= " & Total'Image);
      for J in 1 .. Wrote loop
         if Out_A (First + J - 1) /= Exp (Exp'First + J - 1) then
            Same := False;
         end if;
      end loop;
      Check (Same, Name & ": span mismatch cap=" & Cap'Image);
      for J in Wrote + 1 .. Cap loop
         if Out_A (First + J - 1) /= Poison then
            Kept := False;
         end if;
      end loop;
      Check (Kept, Name & ": entries beyond the written ones were modified, cap=" & Cap'Image);
      Free (Out_A);
   end Run_One;

   --  Brief: only exact capacity and one-too-small (used for the big runs of the contracts build,
   --  where every Segment call also executes the cubic ghost specification).
   procedure Run_Case
     (Name  : String;
      N     : Long_Long_Integer;
      B     : Boundary_Array;
      Exp   : Span_Array;
      Brief : Boolean := False)
   is
      Total : constant Long_Long_Integer := Exp'Length;
   begin
      Cases_Run := Cases_Run + 1;
      Run_One (Name, N, B, Exp, Total, 1);            --  exact capacity: Ok
      if not Brief then
         Run_One (Name, N, B, Exp, Total + 3, 1);     --  roomy: Ok, tail untouched
         Run_One (Name, N, B, Exp, Total + 2, 40);    --  Spans'First <> 1
      end if;
      if Total >= 1 then
         Run_One (Name, N, B, Exp, Total - 1, 1);     --  one too small: Overflow
         if not Brief then
            Run_One (Name, N, B, Exp, 0, 1);          --  nothing fits: Overflow
            Run_One (Name, N, B, Exp, Total / 2, 7);
         end if;
      end if;
   end Run_Case;

   --  Compare against the independent model.
   procedure Run_Model_Case (Name : String; N : Long_Long_Integer; B : Boundary_Array) is
      M : Span_Access := Model (N, B);
   begin
      Run_Case (Name, N, B, M.all);
      Free (M);
   end Run_Model_Case;

   ---------------------------------------------------------------------------
   --  Case-file reader
   ---------------------------------------------------------------------------

   function Parse_Vec (Line : String; From : Positive) return Int_Vec_Access is
      Count : Natural := 0;
      In_Num : Boolean := False;
   begin
      for I in From .. Line'Last loop
         if Line (I) in '0' .. '9' then
            if not In_Num then
               Count := Count + 1;
               In_Num := True;
            end if;
         else
            In_Num := False;
         end if;
      end loop;
      declare
         V   : constant Int_Vec_Access := new Int_Vec (1 .. Count);
         K   : Natural := 0;
         Cur : Long_Long_Integer := 0;
      begin
         In_Num := False;
         for I in From .. Line'Last + 1 loop
            if I <= Line'Last and then Line (I) in '0' .. '9' then
               Cur := Cur * 10 + Long_Long_Integer (Character'Pos (Line (I)) - Character'Pos ('0'));
               In_Num := True;
            elsif In_Num then
               K := K + 1;
               V (K) := Cur;
               Cur := 0;
               In_Num := False;
            end if;
         end loop;
         return V;
      end;
   end Parse_Vec;

   procedure Process_File (Path : String; Label : String) is
      F      : File_Type;
      Name   : Unbounded_String;
      N      : Long_Long_Integer := 0;
      B_Vec  : Int_Vec_Access := null;
      Local_Cases : Natural := 0;
      Before : constant Natural := Failures;
   begin
      Open (F, In_File, Path);
      while not End_Of_File (F) loop
         declare
            Line : constant String := To_String (Ada.Text_IO.Unbounded_IO.Get_Line (F));
         begin
            if Line'Length >= 5 and then Line (Line'First .. Line'First + 4) = "CASE " then
               Name := To_Unbounded_String (Line (Line'First + 5 .. Line'Last));
            elsif Line'Length >= 2 and then Line (Line'First .. Line'First + 1) = "N " then
               N := Parse_Vec (Line, Line'First + 2) (1);
            elsif Line'Length >= 1 and then Line (Line'First) = 'B' then
               if B_Vec /= null then
                  Free (B_Vec);
               end if;
               B_Vec := Parse_Vec (Line, Line'First + 1);
            elsif Line'Length >= 1 and then Line (Line'First) = 'E' then
               declare
                  E_Vec : Int_Vec_Access := Parse_Vec (Line, Line'First + 1);
                  NB    : constant Natural := B_Vec'Length;
               begin
                  if not Small or else NB <= Small_Boundary_Limit then
                     declare
                        B   : Boundary_Array (1 .. Long_Long_Integer (NB));
                        Exp : Span_Array (1 .. Long_Long_Integer (E_Vec'Length / 2));
                     begin
                        for I in 1 .. NB loop
                           B (Position (I)) := B_Vec (I);
                        end loop;
                        for J in 1 .. E_Vec'Length / 2 loop
                           Exp (Position (J)) :=
                             (Start_Idx => E_Vec (2 * J - 1), End_Idx => E_Vec (2 * J));
                        end loop;
                        Check (E_Vec'Length mod 2 = 0, To_String (Name) & ": odd E list");
                        Run_Case (Label & ":" & To_String (Name), N, B, Exp);
                        Local_Cases := Local_Cases + 1;
                     end;
                  end if;
                  Free (E_Vec);
               end;
            end if;
         end;
      end loop;
      Close (F);
      if B_Vec /= null then
         Free (B_Vec);
      end if;
      Put_Line (Label & ": " & Local_Cases'Image & " cases run, "
                & Natural'Image (Failures - Before) & " failures");
   end Process_File;

   ---------------------------------------------------------------------------
   --  Deterministic PRNG (xorshift64*)
   ---------------------------------------------------------------------------

   Rng_State : Unsigned_64 := 16#9E3779B97F4A7C15#;

   function Rand (Bound : Long_Long_Integer) return Long_Long_Integer is
      X : Unsigned_64 := Rng_State;
   begin
      X := X xor Shift_Right (X, 12);
      X := X xor Shift_Left (X, 25);
      X := X xor Shift_Right (X, 27);
      Rng_State := X;
      return Long_Long_Integer ((X * 16#2545F4914F6CDD1D#) mod Unsigned_64 (Bound));
   end Rand;

   ---------------------------------------------------------------------------
   --  Exhaustive small-N enumeration: every subset of {0..N-1} with at most Max_K elements
   ---------------------------------------------------------------------------

   procedure Exhaustive (N_Max : Natural; Max_K : Natural) is
      Cur    : Boundary_Array (1 .. 8) := (others => 0);
      Total  : Natural := 0;
      Merged : Int_Vec (1 .. 9);
      Exp    : Span_Array (1 .. 9);
      Out_A  : Span_Array (1 .. 40);

      procedure Rec (N : Long_Long_Integer; Depth : Natural; Next_Min : Long_Long_Integer) is
         Count  : Long_Long_Integer;
         Needed : Span_Count;
         Status : Status_Kind;
         Good   : Boolean := True;
      begin
         Model_Into (N, Cur (1 .. Long_Long_Integer (Depth)), Merged, Exp, Count);
         Out_A := (others => Poison);
         Segment (N, Cur (1 .. Long_Long_Integer (Depth)), Out_A, Needed, Status);
         Total := Total + 1;
         if Status /= Boundary_Segmentation.Ok or else Needed /= Count then
            Good := False;
         else
            for J in 1 .. Count loop
               if Out_A (J) /= Exp (J) then
                  Good := False;
               end if;
            end loop;
            for J in Count + 1 .. 40 loop
               if Out_A (J) /= Poison then
                  Good := False;
               end if;
            end loop;
         end if;
         if not Good then
            Check (False, "exhaustive N=" & N'Image & " depth=" & Depth'Image);
         end if;
         if Depth < Max_K then
            for V in Next_Min .. N - 1 loop
               Cur (Position (Depth + 1)) := V;
               Rec (N, Depth + 1, V + 1);
            end loop;
         end if;
      end Rec;
   begin
      for N in 0 .. N_Max loop
         Rec (Long_Long_Integer (N), 0, 0);
      end loop;
      Check (True, "exhaustive");
      Put_Line ("exhaustive: " & Total'Image & " boundary sets (N <= " & N_Max'Image
                & ", <= " & Max_K'Image & " boundaries each)");
   end Exhaustive;

   ---------------------------------------------------------------------------
   --  Hand-written cases with explicit expected values
   ---------------------------------------------------------------------------

   procedure Hand_Case
     (Name : String; N : Long_Long_Integer; B : Boundary_Array; Exp : Span_Array) is
   begin
      Run_Case ("hand:" & Name, N, B, Exp);
      --  and the reference model must agree with the hand-computed expectation too
      declare
         M : Span_Access := Model (N, B);
      begin
         Check (M.all = Exp, "hand:" & Name & ": model disagrees with the hand-computed value");
         Free (M);
      end;
   end Hand_Case;

   procedure Hand_Cases is
      None : constant Span_Array (1 .. 0) := (others => Poison);
      Empty_B : constant Boundary_Array (1 .. 0) := (others => 0);
      function S (A, B : Long_Long_Integer) return Span is (Start_Idx => A, End_Idx => B);
   begin
      Hand_Case ("n0-empty", 0, Empty_B, None);
      Hand_Case ("n1-empty", 1, Empty_B, None);
      Hand_Case ("n5-no-tail (4-0 < 5)", 5, Empty_B, None);
      Hand_Case ("n6-tail (5-0 >= 5)", 6, Empty_B, (1 => S (0, 5)));
      Hand_Case ("b4-skipped", 100, (1 => 4), (1 => S (0, 99)));
      Hand_Case ("b5-kept-but-too-short", 100, (1 => 5), (1 => S (0, 99)));
      Hand_Case ("b9-too-short", 100, (1 => 9), (1 => S (0, 99)));
      Hand_Case ("b10-accepted-no-tail", 11, (1 => 10), (1 => S (0, 10)));
      Hand_Case ("b10-accepted-tail", 100, (1 => 10), (S (0, 10), S (11, 99)));
      Hand_Case ("b10-tail-gap-4", 16, (1 => 10), (1 => S (0, 10)));
      Hand_Case ("b10-tail-gap-5", 17, (1 => 10), (S (0, 10), S (11, 16)));
      Hand_Case ("last-tick-boundary", 50, (1 => 49), (1 => S (0, 49)));
      Hand_Case ("merge: 20 not > 5+15, 21 is", 100, (5, 20, 21), (S (0, 21), S (22, 99)));
      Hand_Case ("merge window is vs last KEPT (5,20,35 -> 5,35)", 100, (5, 20, 35),
                 (S (0, 35), S (36, 99)));
      Hand_Case ("first kept (7) too short: absorbed; 41 merged into 30", 100, (7, 30, 41),
                 (S (0, 30), S (31, 99)));
      Hand_Case ("start carries over a rejected candidate", 100, (12, 24, 40),
                 (S (0, 12), S (13, 40), S (41, 99)));
      Hand_Case ("first boundary < 5 dropped, merge uses kept only", 100, (0, 3, 4, 5, 21),
                 (S (0, 21), S (22, 99)));
   end Hand_Cases;

   ---------------------------------------------------------------------------
   --  Invalid input: Invalid_Input, Needed = 0, output untouched
   ---------------------------------------------------------------------------

   procedure Expect_Invalid (Name : String; N : Long_Long_Integer; B : Boundary_Array) is
      Out_A  : Span_Array (1 .. 5) := (others => Poison);
      Needed : Span_Count;
      Status : Status_Kind;
   begin
      Segment (N, B, Out_A, Needed, Status);
      Check (Status = Invalid_Input, "invalid:" & Name & ": status " & Status'Image);
      Check (Needed = 0, "invalid:" & Name & ": needed");
      Check (Out_A = (1 .. 5 => Poison), "invalid:" & Name & ": output modified");
      Check (not Valid_Input (N, B), "invalid:" & Name & ": Valid_Input says valid");
   end Expect_Invalid;

   procedure Invalid_Cases is
   begin
      Expect_Invalid ("duplicate", 100, (10, 10));
      Expect_Invalid ("decreasing", 100, (20, 10));
      Expect_Invalid ("decreasing-late", 100, (5, 30, 29, 60));
      Expect_Invalid ("equals-N", 100, (10, 100));
      Expect_Invalid ("beyond-N", 100, (10, 5000));
      Expect_Invalid ("N-zero-with-boundary", 0, (1 => 0));
      Expect_Invalid ("first-beyond-N", 10, (1 => 10));
      Expect_Invalid ("beyond-N-then-ok", 10, (11, 12));
   end Invalid_Cases;

   ---------------------------------------------------------------------------
   --  64-bit magnitudes: N up to 2**62, indexes near the top, nothing may overflow
   ---------------------------------------------------------------------------

   procedure Big_Cases is
      Top    : constant Long_Long_Integer := Max_Ticks;      --  2**62
      T40    : constant Long_Long_Integer := 2**40;
      Empty_B : constant Boundary_Array (1 .. 0) := (others => 0);
   begin
      Hand_Case ("n=2**62 empty -> one huge tail", Top, Empty_B, (1 => (0, Top - 1)));
      Hand_Case ("n=2**62 last-tick boundary", Top, (1 => Top - 1), (1 => (0, Top - 1)));
      Hand_Case ("n=2**40 two boundaries", T40, (T40 - 100, T40 - 50),
                 ((0, T40 - 100), (T40 - 99, T40 - 50), (T40 - 49, T40 - 1)));
      Hand_Case ("n=2**62 boundaries near top", Top,
                 (Top - 100, Top - 84, Top - 83, Top - 40, Top - 2),
                 ((0, Top - 100), (Top - 99, Top - 84), (Top - 83, Top - 40), (Top - 39, Top - 2)));
      --  random magnitudes against the independent model
      for Round in 1 .. (if Small then 150 else 1500) loop
         declare
            K_Max : constant Long_Long_Integer := Rand (if Small then 8 else 40);
            Buf   : Boundary_Array (1 .. K_Max);
            Count : Long_Long_Integer := 0;
            Base  : Long_Long_Integer;
            Cur   : Long_Long_Integer;
            N     : Long_Long_Integer;
         begin
            case Rand (4) is
               when 0 => Base := Rand (30);
               when 1 => Base := T40 - Rand (1000);
               when 2 => Base := Rand (2**61);
               when others => Base := Top - 2000 - Rand (1000);
            end case;
            Cur := Base;
            for I in Buf'Range loop
               exit when Cur > Top - 1;
               Buf (I) := Cur;
               Count := Count + 1;
               Cur := Cur + 1 + (case Rand (6) is
                                  when 0 => Rand (4),
                                  when 1 => 4 + Rand (8),
                                  when 2 => 9 + Rand (8),
                                  when 3 => 14 + Rand (6),
                                  when 4 => 20 + Rand (40),
                                  when others => 100 + Rand (1000));
            end loop;
            if Count = 0 then
               N := Long_Long_Integer'Min (Top, Base + Rand (12));
            else
               N := Long_Long_Integer'Max
                 (Buf (Count) + 1, Long_Long_Integer'Min (Top, Cur + Rand (12)));
            end if;
            Run_Model_Case ("big-random-" & Round'Image, N, Buf (1 .. Count));
         end;
      end loop;
   end Big_Cases;

   ---------------------------------------------------------------------------
   --  No cap: 100 battles, then 2 million battles
   ---------------------------------------------------------------------------

   procedure Many_Battles (K : Natural; Label : String) is
      B  : Bound_Access := new Boundary_Array (1 .. Long_Long_Integer (K));
      N  : constant Long_Long_Integer := 20 * Long_Long_Integer (K) + 100;
      M  : Span_Access;
   begin
      for I in B'Range loop
         B (I) := 20 * (I - 1) + 5;
      end loop;
      M := Model (N, B.all);
      Check (M'Length >= K - 1, Label & ": model produced too few spans");
      Check (K < 17 or else M'Length > 16, Label & ": expected more than 16 battles");
      Run_Case (Label, N, B.all, M.all, Brief => Small);
      --  the old MAX_MATCHES = 16 cap is gone: capacity 16 must give Overflow, not truncation
      if M'Length > 16 then
         declare
            Out_A  : Span_Array (1 .. 16) := (others => Poison);
            Needed : Span_Count;
            Status : Status_Kind;
         begin
            Segment (N, B.all, Out_A, Needed, Status);
            Check (Status = Overflow, Label & ": capacity 16 did not report Overflow");
            Check (Needed = M'Length, Label & ": Needed not exact with capacity 16");
         end;
      end if;
      Free (M);
      Free (B);
   end Many_Battles;

   Last_Tick : Ada.Calendar.Time := Ada.Calendar.Clock;

   procedure Tick (Label : String) is
      use type Ada.Calendar.Time;
      Now : constant Ada.Calendar.Time := Ada.Calendar.Clock;
   begin
      Put_Line ("  [" & Label & ": " & Integer'Image (Integer ((Now - Last_Tick) * 1000.0)) & " ms]");
      Last_Tick := Now;
   end Tick;

begin
   if Ada.Command_Line.Argument_Count < 2 then
      Put_Line ("usage: test_segmentation <golden-cases> <synthetic-cases> [small]");
      Ada.Command_Line.Set_Exit_Status (2);
      return;
   end if;
   Small := Ada.Command_Line.Argument_Count >= 3
            and then Ada.Command_Line.Argument (3) = "small";

   Process_File (Ada.Command_Line.Argument (1), "golden");
   Tick ("golden");
   Process_File (Ada.Command_Line.Argument (2), "synthetic");
   Tick ("synthetic");
   Hand_Cases;
   Invalid_Cases;
   Tick ("hand+invalid");
   Big_Cases;
   Tick ("big-magnitudes");
   Many_Battles ((if Small then 18 else 100), "many-battles");
   Tick ("many-battles");
   if not Small then
      Many_Battles (2_000_000, "many-2M");
      Tick ("many-2M");
   end if;
   Exhaustive ((if Small then 14 else 36), (if Small then 3 else 6));
   Tick ("exhaustive");

   Put_Line ("TESTS: cases" & Cases_Run'Image & ", Segment calls" & Calls'Image
             & ", checks" & Checks'Image & ", failures" & Failures'Image);
   if Failures = 0 then
      Put_Line ("PASS");
   else
      Put_Line ("FAIL");
      Ada.Command_Line.Set_Exit_Status (1);
   end if;
end Test_Segmentation;
