#!/bin/bash
# Differential, exhaustive and fuzz tests of the recorder_schema unit.  Finishes in well under 10 seconds.
#   spark/core/recorder_schema/tests/run_tests.sh            tests only
#   spark/core/recorder_schema/tests/run_tests.sh --bench    tests, then the native micro-benchmark (~6 s more)
# Oracles (all generated by gen_cases.py, nothing is copied from the real replays):
#   * real replays  : PRAGMA table_info of every *.sqlite in $REPLAY_DIR (default: the owner's scratch copy);
#                     all must be Ok.  Without the directory the committed fixture real_schema_cases.txt is used.
#   * affinity      : >= 2000 random declared types; expected affinity = what SQLite itself resolves (typeof of
#                     inserted values + CAST), which must also equal the documented rules and a port of
#                     sqlite3AffinityType before the case is written.
#   * mutations     : 6000 mutated schemas (drop/rename/retype/re-case tables and columns, extra tables/columns,
#                     duplicates, empty / huge names, over-limit counts); expected = independent Python reference.
#   * recorder      : the required tables/columns/affinities printed by the Ada unit == lua/main.lua's CREATE
#                     TABLE statements run through SQLite.
# Fast build (no contracts) runs the full workload; contracts build (-gnata: every pre/postcondition executed on
# every call) runs a smaller one.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/../../../tools/env.sh"
cd "$HERE"
START=$(date +%s.%N)
WORK="$(mktemp -d "${TMPDIR:-/tmp}/recorder_schema_tests.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT
REPLAY_DIR="${REPLAY_DIR:-/tmp/claude-0/-home-user-WarbandReplayer/7d5d330f-4ddd-581f-b95d-49a16472cab6/scratchpad/data/replays}"

RC=0
gprbuild -q -P tests.gpr -XCONTRACTS=off & BF=$!
gprbuild -q -P tests.gpr -XCONTRACTS=on & BC=$!
GEN=()
python3 gen_cases.py real "$WORK/real.txt" "$REPLAY_DIR" > "$WORK/gen_real" 2>&1 & GEN+=($!)
python3 gen_cases.py affinity "$WORK/affinity.txt" 2600 > "$WORK/gen_affinity" 2>&1 & GEN+=($!)
python3 gen_cases.py mutations "$WORK/mutations.txt" 6000 > "$WORK/gen_mutations" 2>&1 & GEN+=($!)
python3 gen_cases.py mutations "$WORK/mutations_small.txt" 1500 99 > "$WORK/gen_mutations_small" 2>&1 & GEN+=($!)
python3 gen_cases.py selfcheck > "$WORK/gen_selfcheck" 2>&1 & GEN+=($!)
for P in "${GEN[@]}"; do wait "$P" || RC=1; done
wait $BF || RC=1
wait $BC || RC=1
[ $RC -eq 0 ] || { cat "$WORK"/gen_* 2>/dev/null; echo "BUILD / GENERATION FAILED"; exit 1; }
cat "$WORK/gen_selfcheck" "$WORK/gen_real" "$WORK/gen_affinity" "$WORK/gen_mutations"

bin_off/test_recorder_schema --dump > "$WORK/dump" && python3 gen_cases.py recorder "$WORK/dump" || RC=1
bin_off/test_recorder_schema "$WORK/real.txt" "$WORK/affinity.txt" "$WORK/mutations.txt" > "$WORK/out_fast" 2>&1 & PF=$!
bin_on/test_recorder_schema --small "$WORK/real.txt" "$WORK/affinity.txt" "$WORK/mutations_small.txt" > "$WORK/out_on" 2>&1 & PC=$!
wait $PF || RC=1
wait $PC || RC=1
echo "== fast build (full workload) =="; cat "$WORK/out_fast"
echo "== contracts build (-gnata: every pre/postcondition executed) =="; cat "$WORK/out_on"
if [ "${1:-}" = "--bench" ]; then
  echo "== benchmark =="; bin_off/test_recorder_schema --bench | grep -E '^BENCH|checksum'
fi
printf 'elapsed %.1f s\n' "$(echo "$(date +%s.%N) - $START" | bc -l)"
if [ $RC -eq 0 ]; then echo "ALL TESTS PASSED"; else echo "TESTS FAILED"; exit 1; fi
