#!/usr/bin/env python3
"""
Turns sql/canonical_roster_corpse.sql into a compiled-in C string constant
(sql/canonical_roster_corpse_sql.h), plus its own sha256 as a second string
constant. Run from the Makefile before replay_worker.c is compiled.

Why this exists: the exact same SQL text needs to be usable from three
places - the C engine (a compiled-in string, for the debug SQL terminal and
offline battle.db regeneration), testdata/ground_truth.py (the test oracle),
and battle.db's _table_provenance table (a sha256 identifying which version
of the generator produced a given exported table, so a newer app build can
tell a stale table apart from a current one). Generating the header from the
.sql file - rather than hand-copying the SQL into a C string literal and
separately hand-computing a hash - is what guarantees those three never
drift out of sync with each other or with the .sql file itself.

Usage: gen_canonical_sql_header.py <input.sql> <output.h> <C_IDENTIFIER_PREFIX>
"""
import hashlib
import sys


def c_string_literal(text):
    """Encode `text` as a single C string literal, escaping backslash, quote,
    and newline. SQL comments/whitespace are preserved verbatim (harmless -
    this is compiled as one sqlite3_prepare_v2() call, comments are legal
    SQL) rather than stripped, so the compiled-in string is byte-identical
    to the .sql file's content and the sha256 below is meaningful as "the
    hash of what's actually running", not "the hash of some
    stripped/reformatted derivative of it"."""
    escaped = text.replace('\\', '\\\\').replace('"', '\\"').replace('\r', '')
    lines = escaped.split('\n')
    return '\n'.join(f'    "{line}\\n"' for line in lines)


def main():
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <input.sql> <output.h> <C_IDENTIFIER_PREFIX>", file=sys.stderr)
        sys.exit(1)
    in_path, out_path, prefix = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(in_path, 'r', encoding='utf-8', newline='') as f:
        sql_text = f.read()

    sha256_hex = hashlib.sha256(sql_text.encode('utf-8')).hexdigest()
    literal = c_string_literal(sql_text)

    header = f"""/* Auto-generated by scripts/gen_canonical_sql_header.py from {in_path}.
 * Do not edit by hand - edit {in_path} and rebuild instead. */
#ifndef {prefix}_SQL_H
#define {prefix}_SQL_H

static const char {prefix}_SQL[] =
{literal};

static const char {prefix}_SQL_SHA256[] = "{sha256_hex}";

#endif /* {prefix}_SQL_H */
"""

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)

    print(f"generated {out_path} (sha256={sha256_hex})")


if __name__ == '__main__':
    main()
