name = "spike"
description = ""
version = "0.1.0-dev"

authors = ["not your fucking problem o algo"]
maintainers = ["not your fucking problem o algo <nobody@example.com>"]
maintainers-logins = []
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
gnatprove = "^14.1.1"
